# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-23 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samadhana_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='body',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
