# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-23 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samadhana_app', '0002_disaster_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_for',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='samadhana_app.Disaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
